name: .NET Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore API
        run: dotnet restore
        working-directory: ./DcLocations.Api

      - name: Build API
        run: dotnet build --no-restore
        working-directory: ./DcLocations.Api

      - name: Restore Tests
        run: dotnet restore
        working-directory: ./DcLocations.Tests

      - name: Build Tests
        run: dotnet build --no-restore
        working-directory: ./DcLocations.Tests

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ./DcLocations.Tests